<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup Label="Microsoft.Extensions">
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.CommandLine" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Systemd" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup Label="Runtime libraries">
    <PackageVersion Include="MQTTnet" Version="5.1.0.1559" />
    <PackageVersion Include="Zeroconf" Version="3.7.16" />
    <PackageVersion Include="System.IO.Pipelines" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup Label="Build / source link">
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.107" />
    <PackageVersion Include="MinVer" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup Label="Testing">
    <PackageVersion Include="TUnit" Version="1.43.41" />
    <PackageVersion Include="TUnit.Assertions" Version="1.43.41" />
    <PackageVersion Include="NSubstitute" Version="5.3.0" />
    <PackageVersion Include="NSubstitute.Analyzers.CSharp" Version="1.0.17" />
    <PackageVersion Include="coverlet.msbuild" Version="6.0.4" />
  </ItemGroup>

</Project>
