name: Conventional Commits

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  conventional-commits:
    name: Validate commit messages
    runs-on: ubuntu-latest
    steps:
      - name: Check Conventional Commits
        uses: webiny/action-conventional-commits@7f91b1595ca1951cdb671ddc9f07a49081ec5b69 # v1.4.2
